config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  resources :blogs
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:date, :title, :post)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:title, :name, :mail, :messagge)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Date:</strong>
    <%= blog.date %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= blog.post %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :post, style: "display: block" %>
    <%= form.text_area :post %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
      <%= link_to "Show this blog", blog %>
    </p>
  <% end %>
</div>

<%= link_to "New blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Title:</strong>
    <%= contact.title %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Mail:</strong>
    <%= contact.mail %>
  </p>

  <p>
    <strong>Messagge:</strong>
    <%= contact.messagge %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :mail, style: "display: block" %>
    <%= form.text_field :mail %>
  </div>

  <div>
    <%= form.label :messagge, style: "display: block" %>
    <%= form.text_area :messagge %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contacts</h1>

<div id="contacts">
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "Show this contact", contact %>
    </p>
  <% end %>
</div>

<%= link_to "New contact", new_contact_path %>

app/views/contacts/new.html.erb
<h1 class="display-5">Contáctanos</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Volver al inicio", root_path %>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>

app/views/homes/index.html.erb
<seccion class="secc01">
<h1 class="display-6 titulo1">Este espacio es para contar nuestras historias, historias de árboles, nuestros momentos felices, aciertos, fracasos y miedos. Cómo vemos el futuro y nuestro día a día. </h1>


  <div class="row justify-content-center">
    <%= image_tag "tree01.jpg", id: "img01", class: "col-9" %>
  </div>

</seccion>

<seccion class="secc">
  <div class="Container">
    <div class="row">
      <div class="col">
        <%= image_tag "tree02.jpg", id: "img02", class: "col-12" %>
        <p class="pp">Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
      </div>
      <div class="col align-self-center ">
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iusto sint maiores libero aut porro ea quas aliquam dolores cumque voluptatibus fugit sunt, vitae praesentium maxime minima eos corrupti sed officia!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iusto sint maiores libero aut porro ea quas aliquam dolores cumque voluptatibus fugit sunt, vitae praesentium maxime minima eos corrupti sed officia!</p>
      </div>
    </div>
  </div>
</seccion>


<seccion class="secc">
  <div class="Container">
    <div class="row">
      <div class="col  align-self-center ">
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iusto sint maiores libero aut porro ea quas aliquam dolores cumque voluptatibus fugit sunt, vitae praesentium maxime minima eos corrupti sed officia!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iusto sint maiores libero aut porro ea quas aliquam dolores cumque voluptatibus fugit sunt, vitae praesentium maxime minima eos corrupti sed officia!</p>        
      </div>
      <div class="col">
        <%= image_tag "tree03.jpg", id: "img03", class: "col-12" %>
        <p class="pp">Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
      </div>
    </div>
  </div>
</seccion>

app/views/layouts/_footer.html.erb
<p class="pp">Si quieres saber más, contáctanos</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light lead sticky-top" style="background-color: #101009;" >
  <div class="container-fluid">
    <div class="display-6" style="color: #f2ffcc">
      <%= link_to "Historias de árboles", root_path, class: "nav-link" %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto"></ul>
      <ul class="nav" >
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", blogs_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contacto", new_contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item"  >
          <a class="nav-link">Galería</a>
        </li>
        <div class="row align-items-center">
          <div class="col" >
            <%= link_to (icon('fa-brands', 'facebook', class:"fa-2xl")), "https://www.facebook.com" %>
          </div>
          <div class="col">
            <%= link_to (icon('fa-brands', 'instagram', class:"fa-2xl")), "https://www.instagram.com" %>
          </div>
        </div>
      </ul>
    </div>        
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog01</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://kit.fontawesome.com/d734978624.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
      <footer>
        <%= render "layouts/footer" %>
      </footer>
  <script src="https://unpkg.com/scrollreveal"></script>
  </body>
</html>